### ISSUE TITLE
[member] 実験募集フォームのplace_idをプルダウンで選択できるようにする

### ISSUE THREAD

**Issue by yegawa** [nishidalab/entry_form#106]
複数入力が重そうだったのでid直打ちにしてしまってる。
プルダウンに対応＆リストに無いやつは手入力出来るようにしたい

**Comment by yegawa** [comment]
（ #97 閉じてからです。）

**Comment by okabi** [comment]
あんまり把握できてないんだけど、実験実施場所を複数指定できるようになってるんだっけ。
プルダウンよりチェックボックスとかの方が良いのかな、とちょっと思いました。

**Comment by micom1248** [comment]
あー、チェックボックスの方がいいわ
#97 で複数指定出来るようになるよ

**Comment by yegawa** [comment]
あー、チェックボックスの方がいいわ
#97 で複数指定出来るようになるよ

複数指定するのは、内部的な扱いのため（どのICIEを使うだとか、細かい設定）
外向きには部屋情報くらいしか出さないつもり

**Comment by silver-1347** [comment]
https://ja.stackoverflow.com/questions/14891/rails%E3%81%AE%E3%83%95%E3%82%A9%E3%83%BC%E3%83%A0%E3%81%A7%E3%83%9E%E3%83%AB%E3%83%81%E3%83%81%E3%82%A7%E3%83%83%E3%82%AF%E3%83%9C%E3%83%83%E3%82%AF%E3%82%B9%E3%82%92%E5%AE%9F%E7%8F%BE%E3%81%97%E3%81%9F%E3%81%84
http://blog.halenohi.jp/development/2014/04/rails-has-many-through-nested-attributers-form
これを使えば実装できそう

**Comment by silver-1347** [comment]
つまり気味なのでアドバイスもらえるとありがたいです

http://blog.halenohi.jp/development/2014/04/rails-has-many-through-nested-attributers-form
ここを参考にしながら実装を試みてますがここの方法をベタに適用すると `place` テーブル内の全てにたいしてチェックボックスを作成しています。 `room` のIDを(プルダウンなりで)先に決めているのでそれに合わせて動的に表示するチェックボックスを変えるのがベストなのかと思いますが、これをうまく実現する方法がわからなくて詰まっています。

あと、チェックボックス用のスタイルの適用の仕方がいまいちわからないので、cssやscssのどこを参照すれば良いのか教えてもらえるとありがたいです。

**Comment by silver-1347** [comment]
とりあえず機能するところまでは持ってこれました。

残り見た目を整えるところについて2点、助言いただければと思います。
+ チェックボックス用のヘルパーの実装が思いつかないので手助けが欲しいです。
+ `_ex_place_form.html.erb` はサイトを参考にしながら作ったのですが、このままだとヘルパーを作成してもうまく活用できない形になってしまうのですが何か改良案はないでしょうか。

**Comment by yegawa** [comment]
Ajax使って毎回必要な分だけ取りに行くの良いね、バイト先では逆にサーバとの通信減らすことしか考えてなかったからそういう実装思いつかんかった。

とりあえずヘルパー実装してみたんだけど、新たにJSからHTMLを取りに行ってるから
`form` をもってこれないのが痛いね（後者の箇条書きはこのことを言ってるのかな）
ちょっと後者については考え直します

**Comment by yegawa** [comment]
すいません、js.erbのファイルにデバッグ用の `console.log` 入れっぱにしてました
