### ISSUE TITLE
マイページのカレンダーから実験情報を見られるようにしたい(被験者)

### ISSUE THREAD

**Issue by okabi** [nishidalab/entry_form#43]
`mypage` で実験への応募状況をカレンダーで見られるようになっているが、
「○○実験」としか表示されていないので、「○○:○○～○○:○○ ○○実験」と表示変更した上で、
ボタンをクリックすることで実験詳細を表示できると嬉しい。
(実験内容だけポップアップするみたいなのがベストかな？)

**Comment by silver-1347** [comment]
`hint.css` をgemで導入できたのでそれを使ってマウスオーバーで実験の詳細を表示しようという方針で試しているのですが、カレンダー上の項目にスタイル適用するとどうも挙動がおかしいです(ポップアップがしようとするがすぐに消える)。
`calendario` との相性が悪いのでしょうか？
導入したのはこれです
https://github.com/kiurchv/hint
