### ISSUE TITLE
メールアドレスを更新できるようにする(被験者)

### ISSUE THREAD

**Issue by okabi** [nishidalab/entry_form#46]
設定画面からメールアドレスも更新できるようにしたい。
更新時には有効なメールアドレスか確認するために、仮更新→メール送信→本更新という手順を踏みたい。
see also #33

**Comment by silver-1347** [comment]
`participant` に `new_email` カラムを追加して仮更新では `new_email` に入れて本更新時に `email` を更新するように実装しているところなのですが、 `new_email` のバリデーションでつまづいてます。 `email` と同様のものにするとnilがデフォルトで入ってバリデーションにひっかかり、かといって `allow_blank: true` とすると空文字列を通してしまうといった感じにどうもいい方法が浮かびません。
そもそも `new_email` を追加する必要があるのかというところからアドバイスもらえたらと思います。

**Comment by yegawa** [comment]
確かに難しそう…
パッと思いついたのが
`new_email:string` と `changing_email:boolean` を追加して、
メルアド変更時に
```
new_email = hoge@b.c
changing_email = ture
```
本更新で
```
email = new_email
new_email = nil
changing_email = false
```
でemailにnilが入ってしまうのを回避する感じかなあ

**Comment by silver-1347** [comment]
`changing_email == true` 時のみ `new_email` のバリデーションを有効にすることってできますか？

**Comment by silver-1347** [comment]
すいません、調べたらすぐに見つかりました。これでやってみます
