### ISSUE TITLE
学部・研究科IDと名称を結びつける

### ISSUE THREAD

**Issue by okabi** [nishidalab/entry_form#47]
`Participant.faculty` で指定している数値(ID)と実際の学部・研究科名を結び付けられるようにしたい。

**Comment by silver-1347** [comment]
実装方法について助言をいただきたいです。
今``Faculty``テーブルを追加して``Participant``に``Faculty``の外部キーを持たせることで実装しようと考えているのですが、railsでは外部キーには接尾語``_id``をつけなければならないようで名前を変更しないといけないのかというところで詰まってます。
名前変更をすると他に``Participant.faculty``を使っている部分にも関わってくるので、いろんなところを修正しなければならなくなり、さすがにまずいかと思うのですがどうでしょうか。

**Comment by okabi** [comment]
たしかに `Participant.faculty` をすべて `Participant.faculty_id` に変えないとダメですね…。
大きな修正になりそうですが、それでも大丈夫なようにテストを書いているので思い切って修正をお願いしたいです。
今のところ `faculty` はあまり使われていないので基本的には単純な置換で OK で、それで上手くいかないのは `participants#create` `participants#update` くらいだと思います。view 側で name を変える必要が出てくるかな？（例: `:faculty` -> `:faculty_id` ）
適宜テストも書き換える必要が出てくるかと思います。
また詰まったら教えてください。

**Comment by silver-1347** [comment]
わかりました。その方針でできるところまでやってみます。

**Comment by silver-1347** [comment]
`faculty`から`faculty_id`への変換はテスト通る程度には終わってviewを修正し始めました。
そこで`app/view/participants/_form.html.erb`の
`<%= form_select f, :faculty_id, '学部・研究科', {} %>`を
`<%= f.collection_select :faculty_id, Faculty.all, :id, :name, :prompt => true%>`
に変更したのですがこれだとレイアウトが他と異なってしまいます。何か良い方法はないですか？

**Comment by okabi** [comment]
`form_select` はレイアウトを統一するために独自に実装した helper メソッドなので、
定義を見に行くと解決策が分かると思います ☺️

**Comment by silver-1347** [comment]
なんとかなりました、ありがとうございます！
