### ISSUE TITLE
無効な生年月日でも通ってしまう(被験者)

### ISSUE THREAD

**Issue by okabi** [nishidalab/entry_form#51]
たとえば生年月日を 6月31日 で登録するとバリデーションを通過してしまい、7月1日 扱いになってしまう。
無効な生年月日の場合バリデーションで弾きたい。

**Comment by silver-1347** [comment]
```
  test "birth should reject invalid date" do
    @participant.birth = '1990-2-31'
    assert_not @participant.valid?
  end
```
というようなテストを用意しようとしたのですが、 `participant.validate_birth` を特に変更することなく通ってしまうんですが何が原因なんでしょうか。

**Comment by okabi** [comment]
動的解析しただけですが、手元で色々試した感じ、恐らく `birth` に文字列を代入する場合は
まず `Date` 型への変換が発生するので、validation に辿り着く前に引っかかっているのではないかと思います。
`participant.validate_birth` 変更前のコードで、テストにおいて
```
    @participant.birth= { 1 => '1990', 2 => '2', 3 => '31' }
```
としたところ、 `Sat, 03 Mar 1990` に変換されて valid になっていました。

**Comment by silver-1347** [comment]
`birth` のキャスト前が文字列とハッシュ以外の場合ってありますか？ないのであればハッシュの場合についてチェックをすれば良いということなので現在コミットしている部分で対応できると思います。

**Comment by okabi** [comment]
たぶん無いと思います。僕もそれで大丈夫だと思います！
