### ISSUE TITLE
予定が入っている被験者は退会できないようにする

### ISSUE THREAD

**Issue by okabi** [nishidalab/entry_form#64]
拒否されていない `Schedule` や `Event` が存在する `Participant` は、
設定画面の「今、アカウントを削除する」ボタンを押せないようにしたい。

**Comment by silver-1347** [comment]
今ボタンを非表示にすることでボタンを押せなくしようとしてるのですが、これだとdeactivateへのリンクがなくなって``participants_deactivate_test.rb``20行目のテストが通らなくなります。これは実装の方針を変えるべきでしょうか。

**Comment by okabi** [comment]
確認ありがとう。
この場合はテストを条件分けすべきだと思います。
不要なリンクは消すのが親切。
